name: alfred_server
description: backend server for flutter mobile application
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  # sdk: ^3.5.2
  sdk: '>=2.12.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  alfred: ^1.1.1
  html: ^0.15.5
  http: ^1.2.2
  http_parser: ^4.1.1
  intl: ^0.19.0
  io: ^1.0.4
  path: ^1.9.1
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  uri: ^1.0.0
  xml: ^6.5.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
