FROM python:3.10.13-slim-bullseye

RUN apt-get update && apt-get install -y cron

WORKDIR /app

COPY algorithm/requirements.txt /app/

RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt

COPY algorithm/ /app/

RUN mkdir -p /var/log && touch /var/log/cron.log

RUN chmod 666 /var/log/cron.log

RUN echo "0 */3 * * * python /app/lstm.py >> /var/log/cron.log 2>&1" > /etc/cron.d/lstm-cron

RUN chmod 0644 /etc/cron.d/lstm-cron

CMD cron && tail -f /var/log/cron.log
