pipeline {
    agent any

    environment {
        REPO_URL = 'https://github.com/kmin1231/lstm_mobile.git'
        GIT_CREDENTIALS = 'github-ssh-key'
        DOCKER_IMAGE_NAME = 'lstm-jenkins'
        CONTAINER_NAME = 'lstm-jenkins-container'
        DOCKER_REGISTRY = 'docker.io'
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    git credentialsId: GIT_CREDENTIALS, url: REPO_URL, branch: 'main'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -f algorithm/Dockerfile.jenkins -t $DOCKER_IMAGE_NAME . --no-cache"
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    sh "docker ps -a -q -f name=$CONTAINER_NAME | xargs -r docker rm -f"
                    sh "docker run --rm --name $CONTAINER_NAME $DOCKER_IMAGE_NAME"
                    sh "docker logs -f $CONTAINER_NAME"
                    sh 'sleep 10'
                }
            }
        }

        stage('Push to GitHub') {
            steps {
                script {
                    withCredentials([sshUserPrivateKey(credentialsId: 'github-ssh-key', keyFileVariable: 'SSH_KEY')]) {
                        sh '''
                        git config --global user.name "kmin1231"
                        git config --global user.email "kmin91143@gmail.com"
                        git remote set-url origin git@github.com:kmin1231/lstm_mobile.git
                        git add algorithm/*.sqlite3
                        git commit -m "database update by Jenkins"
                        git push origin main
                        '''
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
