apiVersion: apps/v1
kind: Deployment
metadata:
  name: flutter-alfred-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flutter-alfred
  template:
    metadata:
      labels:
        app: flutter-alfred
    spec:
      containers:
      - name: flutter-web-container
        image: edenminkim/flutter-web-app:latest
        ports:
        - containerPort: 85
      - name: alfred-server-container
        image: edenminkim/alfred-server:latest
        ports:
        - containerPort: 8090