apiVersion: v1
kind: Service
metadata:
  name: flutter-alfred-service
spec:
  selector:
    app: flutter-alfred
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 85
  - name: alfred
    protocol: TCP
    port: 8090
    targetPort: 8090
  type: LoadBalancer
