apiVersion: v1
kind: Service
metadata:
  name: flutter-app-service
spec:
  selector:
    app: flutter-app
  ports:
    - name: http
      protocol: TCP
      port: 82
      targetPort: 8181
  type: LoadBalancer
