name: Run Python LSTM Script & Update Database

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-lstm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -f algorithm/Dockerfile -t lstm-script algorithm/

    - name: Run Docker container
      run: |
        docker run --name lstm-container -d lstm-script

    - name: Commit and Push SQLite Database file to GitHub
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add algorithm/lstm_predictions.sqlite3
        git commit -m "update: database file"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
