name: Run Python LSTM Script & Update Database

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  run-lstm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -f algorithm/Dockerfile -t lstm-script algorithm/

    - name: Run Docker container
      run: |
        docker run --name lstm-container -d lstm-script
        docker wait lstm-container

    - name: Wait for container to start
      run: |
        sleep 10

    - name: Check container logs
      run: |
        docker logs -f lstm-container

    - name: Check directory inside container
      run: |
        docker start lstm-container
        docker exec lstm-container ls -l /app
        docker exec lstm-container ls -l /app/algorithm

    - name: Ensure SQLite file exists
      run: |
        if docker exec lstm-container test -f /app/algorithm/lstm_predictions.sqlite3; then
          echo "Database file found.";
        else
          echo "Database file NOT found. Available files are as follows:";
          docker exec lstm-container ls -l /app/algorithm;
          exit 1;
        fi

    - name: Copy SQLite file from container
      run: |
        docker cp lstm-container:/app/algorithm/lstm_predictions.sqlite3 algorithm/

    - name: Commit and Push SQLite Database file to GitHub
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/kmin1231/lstm_mobile.git
        git add algorithm/lstm_predictions.sqlite3
        git commit -m "update: database file"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
